### Bulkheads - calculate fibonacci
GET http://localhost:8080/api/bulkheads/calculate/50

### Bulkheads - calculate nothing
GET http://localhost:8080/api/bulkheads/calculate/nothing

### Timeouts - test timeout
GET http://localhost:8080/api/timeouts/timeout

### CircuitBreaker - calculate fibonacci
GET http://localhost:8080/api/cbreaker